classDiagram
    class UserModel{
        string UserId
        string UserName
        string Email
        datetime RegDate
        datetime ExpiredDate
        bool IsExpired
        bool IsVerified
    }