CREATE TABLE OFTA_BulkSign(
    BulkSignId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_BulkSign_BulkSignId DEFAULT(''),
    BulkSignDate VARCHAR(10) NOT NULL CONSTRAINT DF_OFTA_BulkSign_BulkSignDate DEFAULT('3000-01-01'),
    UserOftaId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_BulkSign_UserOftaId DEFAULT(''),
    BulkSignState BIT NOT NULL CONSTRAINT DF_OFTA_BulkSignDoc_BulkSignState DEFAULT(0),
    DocCount INT NOT NULL CONSTRAINT DF_OFTA_BulkSign_DocCount DEFAULT(0),
    
    CONSTRAINT PK_OFTA_BulkSign PRIMARY KEY CLUSTERED(BulkSignId)
)
GO