CREATE TABLE OFTA_DocTypeTag(
    DocTypeId VARCHAR(5) NOT NULL CONSTRAINT OFTA_DocTypeTagModel_DocTypeId DEFAULT(''),
    Tag VARCHAR(20) NOT NULL CONSTRAINT OFTA_DocTypeTagModel_Tag DEFAULT(''),
    
    CONSTRAINT PK_OFTA_DocTypeTag PRIMARY KEY CLUSTERED(DocTypeId, Tag)
)
GO
