CREATE TABLE OFTA_DocScope(
    DocId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_DocScope_DocId DEFAULT(''),
    ScopeType INT NOT NULL CONSTRAINT DF_OFTA_DocScope_ScopeType DEFAULT(0),
    UserOftaId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_DocScope_UserOftaId DEFAULT(''),
    TeamId VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_DocScope_TeamId DEFAULT(''),

    CONSTRAINT PK_OFTA_DocScope PRIMARY KEY CLUSTERED(DocId, UserOftaId, TeamId)
)