CREATE TABLE [dbo].[OFTA_ParamNo]
(
    Prefix VARCHAR(10) NOT NULL CONSTRAINT DF_OFTA_ParamNo_Prefix DEFAULT(''),
    HexVal VARCHAR(20) NOT NULL CONSTRAINT DF_OFTA_ParamNo_HexVal DEFAULT(''),

    CONSTRAINT PK_OFTA_ParamNo_Prefix PRIMARY KEY CLUSTERED (Prefix)
)
