CREATE TABLE OFTA_UserOfta(
    UserOftaId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_UserOfta_UserOftaId DEFAULT(''),
    UserOftaName VARCHAR(50) NOT NULL CONSTRAINT DF_OFTA_UserOfta_UserOftaName DEFAULT(''),
    Email VARCHAR(50) NOT NULL CONSTRAINT DF_OFTA_UserOfta_Email DEFAULT(''),
    IsVerified BIT NOT NULL CONSTRAINT DF_OFTA_UserOfta_IsVerified DEFAULT(0),
    VerifiedDate DATETIME NOT NULL CONSTRAINT DF_OFTA_UserOfta_VerifiedDate DEFAULT('3000-01-01'),
    ExpiredDate DATETIME NOT NULL CONSTRAINT DF_OFTA_UserOfta_ExpiredDate DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_OFTA_UserOfta PRIMARY KEY(UserOftaId)
)
GO

CREATE UNIQUE INDEX IX_OFTA_UserOfta_Email 
    ON OFTA_UserOfta(Email)
    INCLUDE(UserOftaId)
    WITH(FILLFACTOR = 75)
GO