CREATE TABLE OFTA_Team(
    TeamId VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_Team_TeamId DEFAULT(''),
    TeamName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_Team_TeamName DEFAULT(''),
    
    CONSTRAINT PK_OFTA_Team PRIMARY KEY CLUSTERED(TeamId)
)