CREATE TABLE OFTA_User(
    UserId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_User_UserId DEFAULT(''),
    UserName VARCHAR(50) NOT NULL CONSTRAINT DF_OFTA_User_UserName DEFAULT(''),
    Email VARCHAR(50) NOT NULL CONSTRAINT DF_OFTA_User_Email DEFAULT(''),
    IsVerified BIT NOT NULL CONSTRAINT DF_OFTA_User_IsVerified DEFAULT(0),
    VerifiedDate DATETIME NOT NULL CONSTRAINT DF_OFTA_User_VerifiedDate DEFAULT('3000-01-01'),
    ExpiredDate DATETIME NOT NULL CONSTRAINT DF_OFTA_User_ExpiredDate DEFAULT('3000-01-01'),
    
    CONSTRAINT PK_OFTA_User PRIMARY KEY(UserId)
)
GO

CREATE UNIQUE INDEX IX_OFTA_User_Email 
    ON OFTA_User(Email)
    INCLUDE(UserId)
    WITH(FILLFACTOR = 75)
GO