CREATE TABLE OFTA_KlaimBpjsDoc(
    KlaimBpjsId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_KlaimBpjsId DEFAULT(''),
    KlaimBpjsDocId VARCHAR(16) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_KlaimBpjsDocId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_NoUrut DEFAULT(0),
    DocTypeId VARCHAR(5) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_DocTypeId DEFAULT(''),
    DocTypeName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_DocTypeName DEFAULT(''),
    DocId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_DocId DEFAULT(''),
    DocUrl VARCHAR(255) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_DocUrl DEFAULT(''),
    PrintOutReffId VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_PrintOutReffId DEFAULT(''),
    PrintState INT NOT NULL CONSTRAINT DF_OFTA_KlaimBpjsDoc_PrintState DEFAULT(0),
     
    CONSTRAINT PK_OFTA_KlaimBpjsDoc PRIMARY KEY CLUSTERED (KlaimBpjsDocId),
)
