
CREATE TABLE OFTA_WorkListBpjs(
    OrderKlaimBpjsId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_OrderKlaimBpjsId DEFAULT(''),
    OrderKlaimBpjsDate DATETIME NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_OrderKlaimBpjsDate DEFAULT(''),
    KlaimBpjsId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_WorkListBpjs_KlaimBpjsId DEFAULT(''),
    WorkState INT NOT NULL CONSTRAINT DF_OFTA_KlaimBpjs_WorkState DEFAULT(0),
    RegId VARCHAR(10) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_RegId DEFAULT(''),
    PasienId VARCHAR(15) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_PasienId DEFAULT(''),
    PasienName VARCHAR(50) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_PasienName DEFAULT(''),
    NoSep VARCHAR(20) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_NoSep DEFAULT(''),
    LayananName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_LayananName DEFAULT(''),
    DokterName VARCHAR(30) NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_DokterName DEFAULT(''),
    RajalRanap INT NOT NULL CONSTRAINT DF_OFTA_OFTA_WorkListBpjs_RajalRanap DEFAULT(0),
    
    CONSTRAINT PK_OFTA_OFTA_WorkListBpjs PRIMARY KEY CLUSTERED(OrderKlaimBpjsId),
)
GO