CREATE TABLE OFTA_Post(
    PostId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Post_PostId DEFAULT(''),
    PostDate DATETIME NOT NULL CONSTRAINT DF_OFTA_Post_PostDate DEFAULT('3000-01-01'),
    UserOftaId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Post_UserOftaId DEFAULT(''),
    Msg VARCHAR(2048) NOT NULL CONSTRAINT DF_OFTA_Post_Msg DEFAULT(''),
    DocId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Post_DocId DEFAULT(''),
    CommentCount INT NOT NULL CONSTRAINT DF_OFTA_Post_CommentCount DEFAULT(0),
    LikeCount INT NOT NULL CONSTRAINT DF_OFTA_Post_LikeCount DEFAULT(0),
    
    CONSTRAINT PK_OFTA_Post PRIMARY KEY CLUSTERED(PostId)
)
GO

CREATE INDEX IX_OFTA_Post_PostDate
    ON OFTA_Post(PostDate, PostId)
    WITH(FILLFACTOR = 95)
GO
