CREATE TABLE OFTA_Comment(
    CommentId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Comment_CommentId DEFAULT(''),
    CommentDate DATETIME NOT NULL CONSTRAINT DF_OFTA_Comment_CommentDate DEFAULT('3000-01-01'),
    PostId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Comment_PostId DEFAULT(''),
    UserOftaId VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Comment_UserOftaId DEFAULT(''),
    Msg VARCHAR(2048) NOT NULL CONSTRAINT DF_OFTA_Comment_Msg DEFAULT(''),
    ReactCount VARCHAR(13) NOT NULL CONSTRAINT DF_OFTA_Comment_ReactCount DEFAULT(0),
    
    CONSTRAINT PK_OFTA_Comment PRIMARY KEY CLUSTERED(CommentId)
)
GO

CREATE INDEX IX_OFTA_Comment_PostId
    ON OFTA_Comment (PostId, CommentDate, CommentId)
GO