classDiagram
	class CreateDocCommand{
		<<command>>
		+ string DocTypeId
		+ string UserId
		+ Handler()
		.Create()
		.DocTypeUser()
		.User()
		.AddJurnal(Created)
	}

	class SetFieldDocCommand{
		<<command>>
		+ string DocId
		+ string FieldName
		+ string FieldValue
		+ Handler()
		.Load(docId)
		.SetField(fieldName, fieldValue)
		.Build()

	}

	class ClearFieldDocCommand{
		<<command>>
		+ string DocId
		+ string FieldName
	}

	class AddSigneeDocCommand{
		<<command>>
		+ string DocId
		+ string SignTag
		+ string UserId
		+ string Level		
	}
