sequenceDiagram
    title SKENARIO-4: Bundling Document By Catalog

    participant gugun
    participant OFTA
    participant REMOTECETAK
    participant TEKENAJA
    participant hanum
    participant indah

    Note right of gugun: gugun: petugas klaim bpjs
    Note right of hanum: hanum: dokter lab
    Note right of indah: indah: dokter dpjp

    OFTA ->> gugun : 1. Request Catalog Klaim BPJS
    gugun ->> gugun: 2. Input Catalog Header (Data Pasien)
    OFTA -->> gugun: 3. Download List Document Required by Catalog


    gugun ->> REMOTECETAK: 4. Print Unlisted Document: Hasil Lab
    REMOTECETAK -->> OFTA: 5. Submit Hasil Lab
    OFTA -->> TEKENAJA: 6. Upload Hasil Lab
    TEKENAJA -->> hanum: 7. Notif Sign
    hanum ->> TEKENAJA: 8. Sign HasilLab
    TEKENAJA -->> OFTA : 9. CallBack HasilLab has been signed
    OFTA -->> gugun: 10. Notif HasilLab has been signed
    OFTA ->> gugun: 11. Dowload HasilLab


    gugun ->> OFTA: 13.1 Request Template Surat Selesai Rawat
    OFTA -->> gugun: 13.2 Download Template Surat Selesai Rawat
    gugun ->> gugun: 14. Lengkapi Template Surat Selesai Rawat
    gugun ->> OFTA: 15. Submit Surat Selesai Rawat
    OFTA -->> TEKENAJA: 16. Upload Document
    TEKENAJA -->> indah: 17. Notif Sign Document
    indah ->> TEKENAJA: 18. Sign Document
    TEKENAJA -->> OFTA: 19. CallBack Surat Selesai Rawat has been signed
    OFTA -->> gugun: 20. Notif Surat Selesai Rawat has been signed
    gugun ->> OFTA: 21.1 Request Download Surat Selesai Rawat
    OFTA -->> gugun: 21.2 Dowload Surat Selesai Rawat
